<?php $this->headLink()->appendStylesheet('css/zrad/zrad.home.css') ?>
<div id="bg_pattern">
    <div id="bg_wrapper">
        <div id="container">
            <div id="header">
                <a href ="http://www.zend-rad.com" target="_blank" id="logo" class="replace"><span>Zend Rad</span></a>
            </div>
            <div id="content_top"></div>
            <div class="content">
                <div id="intro">
                    <h1>Proyecto creado con Zend Rad</h1>
                    <p>Ésta es la página principal de tu proyecto. </p>
                </div>
                <div class="services">
                    <div class="s_container">
                        <div class="title"><div id="build_ico"></div><h1>DISEÑE</h1></div>
                        <div class="title_hr"></div>
                        <div class="service_back">
                            <p>El modelado de datos es uno de los elementos más importantes a la hora de iniciar el desarrollo de cualquier proyecto, por ello diseñe su diagramada Entidad Relación (DER) siguiendo la guía de estándares de Zend Rad.  <span><a href="http://www.zend-rad.com" target="_blank">Leer Más</a></span></p>
                        </div>
                    </div>
                    <div class="s_container">
                        <div class="title"><div id="design_ico"></div><h1>GENERE</h1></div>
                        <div class="title_hr"></div>
                        <div class="service_back">
                            <p>Genere los componentes necesarios para su proyecto Zend Framework (modelos, controladores, vistas, etc.) desde su Diagrama Entidad Relación DER, siguiendo la guia "Coding Standard for PHP" desarrollada por Zend.  <span><a href="http://www.zend-rad.com" target="_blank">Leer Más</a></span></p>
                        </div>
                    </div>
                    <div class="s_container">
                        <div class="title"><div id="manage_ico"></div><h1>ACTUALIZE</h1></div>
                        <div class="title_hr"></div>
                        <div class="service_back">
                            <p>Agilize la gestión de cambios actualizando sus componentes (modelos, controladores, vistas, etc.) desde su Diagrama Entidad relación (DER) sincronizando los cambios de su modelo a su proyecto,. Alineandose con cualquier metodología ágil <span><a href="http://www.zend-rad.com" target="_blank">Leer Más</a></span></p>
                        </div>
                    </div>
                </div>
            </div>
            <div id="content_end"></div>
            <div id="footer">
                <div id="copyright">Copyright © <?php echo date('Y') ?> - Zend Rad. Todos los derechos reservados.</div>
            </div>
        </div>
    </div>
</div>