%FORMJSCRIPT%
<div class="zrad-ui-form">
  <h1>Formulario</h1>
  <?php if(count($this->form->getErrorMessages()) > 0) : ?>
  <div class="zrad-ui-form-error ui-state-error ui-corner-all">
    <div style="margin-bottom: 3px;"><strong>Se han encontrado los siguientes Errores:</strong></div>
    <ol>
        <?php foreach($this->form->getErrorMessages() as $message): ?>
        <li><span class="ui-span ui-icon ui-icon-close">&nbsp;</span><label class="error"><?php echo $message ?></label></li>
        <?php endforeach ?>
    </ol>
  </div>
  <?php endif ?>
  <form id="%IDFORM%" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
    <div class="zrad-ui-section">
      <div class="zrad-ui-section-block">
%FORMCONTENT%
        <div class="zrad-ui-form-element ui-widget-content">
          <label class="zrad-label"><em>*</em> Verificación de Palabra
            <span class="zrad-label-small">No se distingue entre mayúsculas y minúsculas.</span>
          </label>
          <div class="zrad-input">
            <div class="zrad-captcha-message">Ingrese los caracteres que logra ver en la imagen:</div>
            <div class="zrad-captcha-image">
              <img src="<?php echo 'resources/captcha/images/' . $this->captcha ?>.png" alt="" />
            </div>
            <div class="zrad-captcha-error">
              <?php echo $this->form->getElement('verificacion') ?>
              <?php if ($this->form->getElement('verificacion')->hasErrors()): ?>
              <label class="zrad-error error" for="verificacion"><?php echo current($this->form->getElement('verificacion')->getMessages()) ?></label>
              <?php else: ?>
              <label class="zrad-error error" for="verificacion">&nbsp;</label>
              <?php endif ?>
            </div>
          </div>
        </div>
      </div>
    </div>    
  </form>
</div>
