%FORMJSCRIPT%
<div class="zrad-ui-title zrad-ui-block ui-widget-header ui-corner-all">
  <div class="zrad-ui-block-icon">
    <span class="ui-icon ui-icon-document-b">&nbsp;</span>
  </div>
  <div class="zrad-ui-block-text"><?php echo $this->title ?></div>
</div>
<div class="zrad-ui-toolbar zrad-ui-block ui-widget-header ui-corner-all">
    <button class="btnBack" type="button">Regresar</button>
    <button class="btnSave" type="button">Guardar</button>
</div>
<div class="zrad-ui-form ui-widget-content ui-corner-all">
  <?php if(count($this->form->getErrorMessages()) > 0) : ?>
  <div class="zrad-ui-form-error ui-state-error ui-corner-all">
    <div style="margin-bottom: 3px;"><strong>Se han encontrado los siguientes Errores:</strong></div>
    <ol>
        <?php foreach($this->form->getErrorMessages() as $message): ?>
        <li><span class="ui-span ui-icon ui-icon-close">&nbsp;</span><label class="error"><?php echo $message ?></label></li>
        <?php endforeach ?>
    </ol>
  </div>
  <?php endif ?>
  <form id="%IDFORM%" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
    <div class="zrad-ui-section">
      <div class="zrad-ui-section-block">
        <fieldset class="ui-widget ui-widget-content ui-corner-all">
          <legend class="ui-widget ui-widget-header ui-corner-all">GENERAL</legend>
%FORMCONTENT%          
        </fieldset>
      </div>
    </div>    
  </form>
</div>
<div class="zrad-ui-toolbar zrad-ui-block ui-widget-header ui-corner-all" style="padding-bottom: 5px">
    <button class="btnBack" type="button">Regresar</button>
    <button class="btnSave" type="button">Guardar</button>
</div>