%FORMJSCRIPT%
<div class="zrad-ui-title zrad-ui-block ui-widget-header ui-corner-all">
  <div class="zrad-ui-block-icon">
    <span class="ui-icon ui-icon-document-b">&nbsp;</span>
  </div>
  <div class="zrad-ui-block-text"><?php echo $this->title ?></div>
</div>
<div class="zrad-ui-toolbar zrad-ui-block ui-widget-header ui-corner-all">
  <button id="btnNew">Nuevo</button>
  <button id="btnEdit">Editar</button>
  <button id="btnDelete">Eliminar</button>
</div>
<table id="tblContent"><tr><td>&nbsp;</td></tr></table>
<div id="panPagination"></div>