<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Mi Proyecto - Zrad</title>
        <style type="text/css">
            body {
                font: 11pt Arial, Helvetica, sans-serif;
                background: url(http://www.zend-rad.com/images/generated/bg_repeat_pattern.jpg) repeat;
                margin: 0;
                padding: 0;
                background-color:#075772
            }

            img {
                border: 0;
            }

            a {
                color: #fff;
                text-decoration: none;

            }

            #bg_pattern {
                background: url(http://www.zend-rad.com/images/generated/bg_pattern.jpg) repeat-x;
            }

            #bg_wrapper {
                width: 100%;
            }

            #container {
                width: 914px;
                margin: auto;
            }

            /* HEADER */

            #header {
                display: inline-block;
                margin: 35px 0 12px 20px;
            }

            #logo {
                float: left;
                height: 51px;
                width: 395px;
                text-indent: -999999px;
                background: url(http://www.zend-rad.com/images/generated/logo.png) no-repeat;
            }

            .replace{
                position:relative;
                /* \*/
                overflow:hidden;
                /* */
            }

            .replace span{
                display:block;
                position:absolute;
                top:0;
                left:0;
                z-index:1;
            }

            /*******CONTENT AREA - HOME *********/

            #content_top {
                display: block;
                height: 31px;
                background: url(http://www.zend-rad.com/images/generated/c_top.png) center no-repeat;
            }

            .content {
                display: inline-block;
                width: 900px;
                height: 100%;
                margin: 0 0 0 7px;
                background: url(http://www.zend-rad.com/images/generated/c_repeat.png) repeat-y;
            }

            #intro {
                display: inline-block;
                width: 520px;
                padding: 0px 40px;
                margin-bottom: 60px;
            }

            #intro h1 {
                font-family: Arial, Helvetica, sans-serif;
                font-size: 13pt;
                font-weight: normal;
                line-height: 1.6em;
                color: #fff;
                text-decoration: none;
                margin: 0 0 10px 0;
            }

            #intro p {
                font-family: Arial, Helvetica, sans-serif;
                font-size: 12px;
                color: #ebebeb;
                line-height: 1.5em;
            }

            #content_end {
                height: 53px;
                background: url(http://www.zend-rad.com/images/generated/c_bottom.png) center no-repeat;
            }

            /* SERVICES SECTION */

            .services {
                padding: 0 25px;
            }

            .s_container {
                display: inline-block;
                width: 280px;
            }

            .services h1 {
                font-family: Arial, Helvetica, sans-serif;
                font-size: 19px;
                font-weight: none;
                color: #fff;
                text-decoration: none;
                text-shadow: 1px 1px 2px #333;
                margin: 0 0 5px 35px;

            }

            #design_ico {
                float: left;
                width: 20px;
                height: 18px;
                margin: 3px 0 0 8px;
                background: url(http://www.zend-rad.com/images/generated/design_icon.png);
            }

            #build_ico {
                float: left;
                width: 22px;
                height: 21px;
                margin: 3px 0 0 8px;
                background: url(http://www.zend-rad.com/images/generated/build_icon.png);
            }

            #manage_ico {
                float: left;
                width: 22px;
                height: 20px;
                margin: 3px 0 0 8px;
                background: url(http://www.zend-rad.com/images/generated/manage_icon.png);
            }

            .title {
                display: inline-block;
                margin-left: 5px;
                width: 271px;
            }

            .title_hr {
                width: 271px;
                height: 4px;
                background: url(http://www.zend-rad.com/images/generated/title_line.png);
            }

            .service_back {
                width: 277px;
                height: 144px;
                background: url(http://www.zend-rad.com/images/generated/services_back.png) no-repeat;
            }

            .service_back p {
                font-family: Arial, Helvetica, sans-serif;
                font-size: 12px;
                color: #ebebeb;
                line-height: 1.6em;
                padding: 0 13px 0px 13px;
            }

            .service_back span {
                font-weight: bold;
                text-decoration: underline;
            }

            /* FOOTER */

            #footer {
                height: 30px;
            }

            #copyright {
                font-size: 12px;
                color: #FFFFFF;
                margin: 20px 0px 0 15px;
            }
        </style>
    </head>
    <body>
        <div id="bg_pattern">
            <div id="bg_wrapper">
                <div id="container">
                    <div id="header">
                        <a href ="http://www.zend-rad.com" id="logo" class="replace"><span>Zend Rad</span></a>
                    </div><!--header-->
                    <div id="content_top"></div>
                    <div class="content">
                        <div id="intro">
                            <h1>Bienvenido a su proyecto con Zend RAD</h1>
                            <p>Esta es la página principal de tu Proyecto.  Read More </p>
                        </div><!--introduction end-->
                        <div class="services">
                            <div class="s_container">
                                <div class="title"><div id="design_ico"></div><h1>DISEÑE</h1></div>
                                <div class="title_hr"></div>
                                <div class="service_back">
                                    <p>Suspendisse pulvinar lectus justo. In vestibulum mollis consequat. Duis posuere, purus vel auctor rutrum, justo ipsum blandit nunc, vitae feugiat dui arcu vitae ipsum. Donec aliquet massa at nisl.  <span>Read More</span></p>
                                </div><!--service back end-->
                            </div><!--s container end-->
                            <div class="s_container">
                                <div class="title"><div id="build_ico"></div><h1>CONSTRUYA</h1></div>
                                <div class="title_hr"></div>
                                <div class="service_back">
                                    <p>Suspendisse pulvinar lectus justo. In vestibulum mollis consequat. Duis posuere, purus vel auctor rutrum, justo ipsum blandit nunc, vitae feugiat dui arcu vitae ipsum. Donec aliquet massa at nisl.  <span>Read More</span></p>
                                </div><!--service back end-->
                            </div><!--s container end-->
                            <div class="s_container">
                                <div class="title"><div id="manage_ico"></div><h1>ACTULIZE</h1></div>
                                <div class="title_hr"></div>
                                <div class="service_back">
                                    <p>Suspendisse pulvinar lectus justo. In vestibulum mollis consequat. Duis posuere, purus vel auctor rutrum, justo ipsum blandit nunc, vitae feugiat dui arcu vitae ipsum. Donec aliquet massa at nisl.  <span>Read More</span></p>
                                </div><!--service back end-->
                            </div><!--s container end-->
                        </div><!--services ends-->
                    </div><!--content end-->
                    <div id="content_end"></div>
                    <div id="footer">
                        <div id="copyright">Copyright © 2010 - Zend Rad. All rights reserved.</div>
                    </div><!--footer ends-->
                </div><!--container ends-->
            </div><!--bgwrapper ends-->
        </div><!--bgpattern ends-->
    </body>
</html>