<?php
$attributesWhiteList = array('class','style','id');
$attr = '';
$attributes = $this->element->getAttribs();
foreach ($attributes as $attrib => $value) {
    if (!in_array($attrib, $attributesWhiteList)){
        //unset($attributes[$attrib]);
    } else {
        $attr .= $attrib . '="' . $value . '" ';
    }
}

$brackets = ($this->element->isArray()) ? '[]' : '';
$belongTo = $this->element->getBelongsTo();
$nameTag = isset($attributes['name']) ? $attributes['name'] : $this->element->getName();
$idTag = isset($attributes['id']) ? $attributes['id'] : $this->element->getName();
$id = (!empty($belongTo)) ? $belongTo . '-' .  $idTag : $idTag;
$name = (!empty($belongTo)) ? $belongTo . '[' .  $nameTag . ']' : $nameTag . $brackets;

?>
<div class="zrad-ui-form-element ui-widget-content">
    <label class="zrad-label"><em><?php if ($this->element->isRequired()): ?>*<?php endif ?></em> <?php echo $this->element->getLabel() ?>
        <span class="zrad-label-small"><?php echo $this->element->getDescription() ?></span>
    </label>
    <div class="zrad-input">
        <textarea cols="30" rows="3" id="<?php echo $id ?>" name="<?php echo $name ?>" <?php echo $attr ?> ><?php echo $this->element->getValue() ?></textarea>
        <?php if ($this->element->hasErrors()): ?>
        <label for="<?php echo $id ?>" class="zrad-error error" generated="true"><?php echo current($this->element->getMessages()) ?></label>
        <?php endif ?>
    </div>
</div>