<?php
$attributesWhiteList = array('class','maxlength');
$attr = '';
$attributes = $this->element->getAttribs();
foreach ($attributes as $attrib => $value) {
    if (!in_array($attrib, $attributesWhiteList)){
        unset($attributes[$attrib]);
    } else {
        $attr .= $attrib . '="' . $value . '"';
    }
}
// Tabs
$belongTo = $this->element->getBelongsTo();
$id = (!empty($belongTo)) ? $belongTo . '-' .  $this->element->getName() : $this->element->getName();
$name = (!empty($belongTo)) ? $belongTo . '[' .  $this->element->getName() . ']' : $this->element->getName();
// Type
$typeClass = explode('_', $this->element->getType());
$type = strtolower(array_pop($typeClass));
?>
<div class="zrad-ui-form-element ui-widget-content">
    <label class="zrad-label"><?php if ($this->element->isRequired()): ?><em>*</em><?php endif ?> <?php echo $this->element->getLabel() ?>
        <span class="zrad-label-small"><?php echo $this->element->getDescription() ?></span>
    </label>
    <div class="zrad-input">
        <input type="<?php echo $type ?>" id="<?php echo $id ?>" name="<?php echo $name ?>" value="<?php echo $this->element->getValue() ?>" <?php echo $attr ?> />
        <?php if ($this->element->hasErrors()): ?>
        <label for="<?php echo $id ?>" class="zrad-error error" generated="true"><?php echo current($this->element->getMessages()) ?></label>
        <?php endif ?>
    </div>
</div>