<?php $this->headLink()->appendStylesheet('css/zrad/zrad.home.css') ?>
<div id="bg_pattern">
    <div id="bg_wrapper">
        <div id="container">
            <div id="header">
                <a href ="<?php echo $this->baseUrl('/') ?>" id="logo" class="replace"><span>Zend Rad</span></a>
            </div>
            <div id="content_top"></div>
            <div class="content">
                <div class="services">
                    <a href="concurso/registro"><img src="images/zrad/bienvenido.jpg" alt="Bienvenido" /></a>
                </div>
            </div>
            <div id="content_end"></div>
            <div id="footer">
                <div id="copyright">Copyright © 2013 - <a href ="http://www.zend-rad.com" target="_blank">Zend Rad</a>. Todos los derechos reservados.</div>
            </div> 
        </div>
    </div>
</div>