<!DOCTYPE HTML>
<html>
    <head>
        <base href="<?php echo $this->ServerUrl($this->baseUrl('/')) ?>" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />        
        <title>Administrador de Contenidos</title>
        <link rel="shortcut icon" href="favicon.ico" />
        <!-- jQuery -->
        <script type="text/javascript" src="js/jquery/jquery-1.8.3.min.js"></script>
        <!-- UI Library -->
        <link type="text/css" href="js/jquery/ui/themes/zrad/jquery-ui-1.10.2.custom.min.css" media="screen" rel="stylesheet" />
        <script type="text/javascript" src="js/jquery/ui/jquery-ui-1.10.2.custom.min.js"></script>
        <script type="text/javascript" src="js/jquery/ui/ui.datepicker-es.js"></script>
        <!-- UI Checkbox -->
        <link type="text/css" href="js/jquery/ui/checkbox/ui.checkbox-ui.radiobutton.css" media="screen" rel="stylesheet" />
        <link type="text/css" href="js/jquery/ui/checkbox/ui.checkbox-ui.radiobutton.style.msoffice.css" media="screen" rel="stylesheet" />
        <script type="text/javascript" src="js/jquery/ui/checkbox/ui.checkbox-ui.radiobutton.js"></script>
        <!-- Validate Library -->
        <script type="text/javascript" src="js/jquery/validate/jquery.validate.min.js"></script>
        <script type="text/javascript" src="js/jquery/validate/lib/jquery.form.js"></script>
        <script type="text/javascript" src="js/jquery/validate/lib/jquery.metadata.js"></script>        
        <!-- Zrad UI -->
        <link href="css/zrad/zrad.ui.css" media="screen" rel="stylesheet" type="text/css" />
        <!-- Helper -->
        <script type="text/javascript" src="js/zrad/zrad.helper.js"></script>
        <!-- BaseUrl -->
        <script type="text/javascript">
            var baseUrl = '<?php echo $this->baseUrl() ?>';
        </script>
        <!-- Dynamic Js / Css -->
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
        <?php echo $this->headStyle() ?>
    </head>
    <body>        
        <?php echo $this->layout()->content ?>
    </body>
</html>