<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
    <head>
        <base href="<?php echo $this->ServerUrl($this->baseUrl('/')) ?>" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="shortcut icon" href="favicon.ico" />
        <title>Zend Rad | Proyecto</title> 
        <script type="text/javascript" src="js/jquery/jquery-1.9.1.min.js"></script>        
        <!-- UI Library -->
        <link type="text/css" href="js/jquery/ui/themes/zrad/jquery-ui-1.10.2.custom.min.css" media="screen" rel="stylesheet" />
        <script type="text/javascript" src="js/jquery/ui/jquery-ui-1.10.2.custom.min.js"></script>
        <script type="text/javascript" src="js/jquery/ui/ui.datepicker-es.js"></script>
        <!-- UI Fileinput -->
        <link type="text/css" href="css/zrad/zrad.fileinput.css" media="screen" rel="stylesheet" />
        <script type="text/javascript" src="js/jquery/ui/fileinput/jquery.fileinput.min.js"></script>
        <!-- Validate Library -->
        <script type="text/javascript" src="js/jquery/validate/jquery.validate.min.js"></script>
        <script type="text/javascript" src="js/jquery/validate/lib/jquery.form.js"></script>
        <script type="text/javascript" src="js/jquery/validate/lib/jquery.metadata.js"></script>
        <script type="text/javascript" src="js/jquery/validate/additional-methods-es.js"></script>
        <script type="text/javascript" src="js/jquery/validate/localization/messages_es.js"></script>
        <!-- Default -->
        <link type="text/css" href="css/zrad/zrad.website.css" media="screen" rel="stylesheet" />
        <link type="text/css" href="css/zrad/zrad.home.css" media="screen" rel="stylesheet" />
        <!-- Zrad -->
        <script type="text/javascript" src="js/zrad/zrad.ui.helper.js"></script>
        <script type="text/javascript" src="js/zrad/zrad.helper.js"></script>
        <script type="text/javascript" src="js/zrad/zrad.loader.js"></script>
        <!-- BaseUrl -->
        <script type="text/javascript">
            var baseUrl = '<?php echo $this->baseUrl() ?>';
        </script>
        <!-- Render All -->
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
        <?php echo $this->headStyle() ?>
        <style type="text/css">
            .ui-widget {font-size: 0.8em}            
            .ui-progressbar-value {background-image: url("images/zrad/pbar-ani.gif")}
            #zrad-loader-ui, .qq-upload-list, #dlgRegistro{display: none}
            .zrad-ui-dialog-valid ul {padding: 0 10px; margin: 0}
            .btn {cursor: pointer}  
            .ui-widget-overlay {opacity:0.3!important;filter:Alpha(Opacity=30);position:fixed;top:0;left:0;width:100%;height:100%}
            iframe{margin: 0;padding: 0;border: 0;}
            form {margin:0;}
        </style>
    </head>
    <body>
        <div id="bg_pattern">
            <div id="bg_wrapper">
                <div id="container">
                    <div id="header">
                        <a href ="<?php echo $this->baseUrl('/') ?>" id="logo" class="replace"><span>Zend Rad</span></a>
                    </div>
                    <div id="content_top"></div>
                    <div class="content">
                        <div id="intro">
                            <h1>Proyecto creado con Zend Rad</h1>                            
                        </div>
                        <div class="services">                            
                            <?php echo $this->layout()->content ?>
                        </div>
                    </div>
                    <div id="content_end"></div>
                    <div id="footer">
                        <div id="copyright">Copyright © 2013 - <a href ="http://www.zend-rad.com" target="_blank">Zend Rad</a>. Todos los derechos reservados.</div>
                    </div>
                </div>
            </div>
        </div>
        <div id="dlgRegistro" class="zrad-ui-dialog-valid">
            <ul>
                <?php if (count($this->errors) > 0): ?>
                <?php foreach ($this->errors as $campo => $error): ?>
                <li><?php echo ucfirst($campo) . '. ' . current($error) ?></li>
                <?php endforeach ?>
                <?php else: ?>
                <li>&nbsp;</li>
                <?php endif ?>                
            </ul>
        </div>
        <div id="zrad-loader-ui">
            <div class="ui-overlay">
                <div class="ui-widget-overlay" style="filter:Alpha(Opacity=50); opacity:0.5;height: 100%; z-index: 100"></div>
                <div class="ui-widget-shadow ui-corner-all" style="width: 202px;height: 72px;margin-top:-36px;margin-left:-101px; position: absolute; left: 50%; top: 50%;"></div>
            </div>
            <div style="position: absolute; width: 188px; height: 60px;margin-top:-29px;margin-left:-94px; left: 50%; top: 50%; padding: 10px; z-index: 100" class="ui-widget ui-widget-content ui-corner-all">
                <div class="ui-dialog-content ui-widget-content" style="background: none; border: 0; padding-bottom: 4px;">Cargando...</div>
                <div>
                    <div class="ui-progressbar-value ui-widget-header ui-corner-left ui-corner-right" style="width: 100%; height: 1.7em;"></div>
                </div>
            </div>
        </div>
    </body>
</html>